/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.palabrapoder.temporizador.vista;

/**
 *
 * @author Fernand
 */
public class FormularioBotones extends javax.swing.JFrame {

    /**
     * Creates new form FormularioBotones
     */
    public FormularioBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        execute = new javax.swing.JButton();
        parar = new javax.swing.JButton();
        jbreinicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlHoDePe = new javax.swing.JLabel();
        jlMinDePeq = new javax.swing.JLabel();
        jlSegDePe = new javax.swing.JLabel();
        jLHoUPe = new javax.swing.JLabel();
        jLMinUPe = new javax.swing.JLabel();
        jlSegUnPeq = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlHoraPeq = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textoMenu = new javax.swing.JLabel();
        textSuperIngre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtInfBtn = new javax.swing.JLabel();
        textBtnInfe = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MINISTERIO PALABRA Y PODER");
        setBackground(new java.awt.Color(33, 45, 62));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(33, 45, 62));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        execute.setBackground(new java.awt.Color(33, 45, 62));
        execute.setForeground(new java.awt.Color(255, 255, 255));
        execute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/palabrapoder/temporizador/recursos/music-player-play.png"))); // NOI18N
        execute.setText("INICIO");
        execute.setActionCommand("run");
        execute.setBorder(null);
        execute.setBorderPainted(false);
        execute.setContentAreaFilled(false);
        execute.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        execute.setFocusPainted(false);
        execute.setHideActionText(true);
        execute.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        execute.setSelected(true);
        execute.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeActionPerformed(evt);
            }
        });
        jPanel3.add(execute, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 100));
        execute.getAccessibleContext().setAccessibleName("run");

        parar.setBackground(new java.awt.Color(33, 45, 62));
        parar.setForeground(new java.awt.Color(255, 255, 255));
        parar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/palabrapoder/temporizador/recursos/stop-button.png"))); // NOI18N
        parar.setText("PARAR");
        parar.setBorderPainted(false);
        parar.setContentAreaFilled(false);
        parar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        parar.setFocusPainted(false);
        parar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        parar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararActionPerformed(evt);
            }
        });
        jPanel3.add(parar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, 100));

        jbreinicio.setBackground(new java.awt.Color(33, 45, 62));
        jbreinicio.setForeground(new java.awt.Color(255, 255, 255));
        jbreinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/palabrapoder/temporizador/recursos/reinicio.png"))); // NOI18N
        jbreinicio.setText("REINICIO");
        jbreinicio.setToolTipText("");
        jbreinicio.setBorderPainted(false);
        jbreinicio.setContentAreaFilled(false);
        jbreinicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbreinicio.setFocusPainted(false);
        jbreinicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreinicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreinicioActionPerformed(evt);
            }
        });
        jPanel3.add(jbreinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 100, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 140));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlHoDePe.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 100)); // NOI18N
        jlHoDePe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHoDePe.setText("0");
        jlHoDePe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlHoDePe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 90));

        jlMinDePeq.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 100)); // NOI18N
        jlMinDePeq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinDePeq.setText("0");
        jlMinDePeq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlMinDePeq, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 70, 90));

        jlSegDePe.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 100)); // NOI18N
        jlSegDePe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSegDePe.setText("0");
        jlSegDePe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlSegDePe, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 70, 90));

        jLHoUPe.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 100)); // NOI18N
        jLHoUPe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHoUPe.setText("0");
        jLHoUPe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLHoUPe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, 90));

        jLMinUPe.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 100)); // NOI18N
        jLMinUPe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMinUPe.setText("0");
        jLMinUPe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLMinUPe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 70, 90));

        jlSegUnPeq.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 100)); // NOI18N
        jlSegUnPeq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSegUnPeq.setText("0");
        jlSegUnPeq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlSegUnPeq, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 70, 90));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlHoraPeq.setFont(new java.awt.Font("sansserif", 1, 40)); // NOI18N
        jlHoraPeq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHoraPeq.setText("0");
        jPanel2.add(jlHoraPeq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 110));

        jPanel4.setLayout(new java.awt.CardLayout());

        textoMenu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textoMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(textoMenu, "card2");

        textSuperIngre.setBackground(new java.awt.Color(240, 240, 240));
        textSuperIngre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textSuperIngre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textSuperIngre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        textSuperIngre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(textSuperIngre, "card3");

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 240, 110));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 45)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 30, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 45)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 30, 40));

        jPanel5.setLayout(new java.awt.CardLayout());

        txtInfBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtInfBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInfBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(txtInfBtn, "card2");

        textBtnInfe.setBackground(new java.awt.Color(240, 240, 240));
        textBtnInfe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textBtnInfe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBtnInfe.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        textBtnInfe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(textBtnInfe, "card3");

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 460, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 490, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_executeActionPerformed

    private void jbreinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbreinicioActionPerformed

    private void pararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioBotones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton execute;
    public javax.swing.JLabel jLHoUPe;
    public javax.swing.JLabel jLMinUPe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JButton jbreinicio;
    public javax.swing.JLabel jlHoDePe;
    public javax.swing.JLabel jlHoraPeq;
    public javax.swing.JLabel jlMinDePeq;
    public javax.swing.JLabel jlSegDePe;
    public javax.swing.JLabel jlSegUnPeq;
    public javax.swing.JButton parar;
    public javax.swing.JTextField textBtnInfe;
    public javax.swing.JTextField textSuperIngre;
    public javax.swing.JLabel textoMenu;
    public javax.swing.JLabel txtInfBtn;
    // End of variables declaration//GEN-END:variables
}
