/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.palabrapoder.temporizador.vista;

/**
 *
 * @author Fernand
 */
public class FormularioNumero extends javax.swing.JFrame {

    /**
     * Creates new form FormularioNumero
     */
    public FormularioNumero() {
        initComponents();
        //this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        horasDecenas = new javax.swing.JLabel();
        minutosUnidad = new javax.swing.JLabel();
        dot4 = new javax.swing.JLabel();
        horasUnidad = new javax.swing.JLabel();
        minutosDecenas = new javax.swing.JLabel();
        dot2 = new javax.swing.JLabel();
        segundosDecenas = new javax.swing.JLabel();
        segundosUnidad = new javax.swing.JLabel();
        dot1 = new javax.swing.JLabel();
        dot3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lhora = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textoIngresado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textoInferior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel9.setBackground(new java.awt.Color(2, 10, 57));

        jPanel10.setBackground(new java.awt.Color(23, 150, 207));
        jPanel10.setPreferredSize(new java.awt.Dimension(1524, 421));

        horasDecenas.setBackground(new java.awt.Color(23, 150, 207));
        horasDecenas.setFont(new java.awt.Font("Tahoma", 1, 350)); // NOI18N
        horasDecenas.setForeground(new java.awt.Color(255, 255, 255));
        horasDecenas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horasDecenas.setText("0");
        horasDecenas.setToolTipText("");

        minutosUnidad.setFont(new java.awt.Font("Tahoma", 1, 350)); // NOI18N
        minutosUnidad.setForeground(new java.awt.Color(255, 255, 255));
        minutosUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minutosUnidad.setText("0");

        dot4.setFont(new java.awt.Font("Times New Roman", 1, 120)); // NOI18N
        dot4.setForeground(new java.awt.Color(255, 255, 255));
        dot4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dot4.setText("•");
        dot4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        horasUnidad.setFont(new java.awt.Font("Tahoma", 1, 350)); // NOI18N
        horasUnidad.setForeground(new java.awt.Color(255, 255, 255));
        horasUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horasUnidad.setText("0");
        horasUnidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        horasUnidad.setPreferredSize(new java.awt.Dimension(200, 300));
        horasUnidad.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        minutosDecenas.setFont(new java.awt.Font("Tahoma", 1, 350)); // NOI18N
        minutosDecenas.setForeground(new java.awt.Color(255, 255, 255));
        minutosDecenas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minutosDecenas.setText("0");
        minutosDecenas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minutosDecenas.setPreferredSize(new java.awt.Dimension(200, 301));
        minutosDecenas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        dot2.setFont(new java.awt.Font("Times New Roman", 1, 120)); // NOI18N
        dot2.setForeground(new java.awt.Color(255, 255, 255));
        dot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dot2.setText("•");
        dot2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        segundosDecenas.setFont(new java.awt.Font("Tahoma", 1, 350)); // NOI18N
        segundosDecenas.setForeground(new java.awt.Color(255, 255, 255));
        segundosDecenas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segundosDecenas.setText("0");

        segundosUnidad.setFont(new java.awt.Font("Tahoma", 1, 350)); // NOI18N
        segundosUnidad.setForeground(new java.awt.Color(255, 255, 255));
        segundosUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segundosUnidad.setText("0");

        dot1.setFont(new java.awt.Font("Times New Roman", 1, 120)); // NOI18N
        dot1.setForeground(new java.awt.Color(255, 255, 255));
        dot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dot1.setText("•");
        dot1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dot3.setFont(new java.awt.Font("Times New Roman", 1, 120)); // NOI18N
        dot3.setForeground(new java.awt.Color(255, 255, 255));
        dot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dot3.setText("•");
        dot3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(horasDecenas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(horasUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dot1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(dot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(minutosDecenas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minutosUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dot3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dot4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(segundosDecenas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(segundosUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(horasUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horasDecenas, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutosDecenas, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minutosUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(segundosDecenas, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(segundosUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dot3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dot1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dot4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dot2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 153, 0), new java.awt.Color(204, 153, 0)));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        lhora.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        lhora.setForeground(new java.awt.Color(255, 255, 255));
        lhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lhora.setText("0");
        lhora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lhora, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 153, 0), new java.awt.Color(204, 153, 0)));

        textoIngresado.setBackground(new java.awt.Color(0, 0, 0));
        textoIngresado.setFont(new java.awt.Font("sansserif", 1, 90)); // NOI18N
        textoIngresado.setForeground(new java.awt.Color(255, 255, 255));
        textoIngresado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIngresado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoIngresado, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoIngresado, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 153, 0), new java.awt.Color(204, 153, 0)));

        textoInferior.setBackground(new java.awt.Color(255, 255, 255));
        textoInferior.setFont(new java.awt.Font("SansSerif", 1, 100)); // NOI18N
        textoInferior.setForeground(new java.awt.Color(255, 255, 255));
        textoInferior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(textoInferior, javax.swing.GroupLayout.DEFAULT_SIZE, 1845, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(textoInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1885, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(614, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioNumero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel dot1;
    public javax.swing.JLabel dot2;
    public javax.swing.JLabel dot3;
    public javax.swing.JLabel dot4;
    public javax.swing.JLabel horasDecenas;
    public javax.swing.JLabel horasUnidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel lhora;
    public javax.swing.JLabel minutosDecenas;
    public javax.swing.JLabel minutosUnidad;
    public javax.swing.JLabel segundosDecenas;
    public javax.swing.JLabel segundosUnidad;
    public javax.swing.JLabel textoInferior;
    public javax.swing.JLabel textoIngresado;
    // End of variables declaration//GEN-END:variables
}
